### ISSUE TITLE
Voip CallMeBot - Error with variable call_number using @user 

### ISSUE THREAD

**Issue by stegazzi** [jumping2000/notifier#14]
Hello,

i have configured the Centro Notifiche for working with voip with callmebot.... and it is working fine.

In my system the call notification are disabled ...and for some automation i wanted to add a phone call (example: alarm)....For this , thanks to Caio , i use the variable called_number with my @username.
But when i validate my config i have :

_- Error: Testing configuration at /config:
ERROR:homeassistant.util.yaml.loader : while scanning for the next token
found character '@' that cannot start any token
  in "/config/packages......_

I tried to use " and '  ("@user" and '@user') but is not working. For now i am using priority 1 that work great. Can you help me ?!

Thanks
Stefano
@stegazzi

**Comment by jumping2000** [comment]
called_number is used for VoIP call not for Telegram Call.

**Comment by caiosweet** [comment]
Try using the phone number instead of the user account
Input text on fronted empty and switch tel on
In dev-tools services try:
message: message to send
called_number: '+39.....'

or

put the number in the input text and activate the switch tel (on)
In dev-tools services try:
message: message to send
priority: 1

or
input text empty and switch tel Off
In dev-tools services try:
message: message to send
called_number: '+39YOURPHONE'
priority: 1

**Comment by jumping2000** [comment]
Callme BOT behaviour changed
